-- CreateTable
CREATE TABLE "Buyer" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" STRING NOT NULL,
    "last_name" STRING NOT NULL,
    "phone_number" STRING NOT NULL,
    "gender" STRING NOT NULL,
    "date_of_birth" TIMESTAMP(3) NOT NULL,
    "auth_id" INT4 NOT NULL,

    CONSTRAINT "Buyer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Seller" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" STRING NOT NULL,
    "last_name" STRING NOT NULL,
    "phone_number" STRING NOT NULL,
    "gender" STRING NOT NULL,
    "date_of_birth" TIMESTAMP(3) NOT NULL,
    "store_id" INT4 NOT NULL,
    "auth_id" INT4 NOT NULL,

    CONSTRAINT "Seller_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Auth" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "token" STRING,
    "token_expiry" TIMESTAMP(3),
    "is_active" BOOL NOT NULL DEFAULT true,
    "is_email_verified" BOOL NOT NULL DEFAULT false,
    "is_phone_verified" BOOL NOT NULL DEFAULT false,
    "reset_token" STRING,
    "reset_token_expiry" TIMESTAMP(3),
    "last_login" TIMESTAMP(3),

    CONSTRAINT "Auth_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Store" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "store_name" STRING NOT NULL,
    "store_description" STRING,
    "supports_delivery" BOOL NOT NULL,
    "store_delivery_radius" INT4 NOT NULL,
    "address" STRING NOT NULL,
    "city" STRING NOT NULL,
    "state_province" STRING NOT NULL,
    "zipcode" STRING NOT NULL,
    "country" STRING NOT NULL,

    CONSTRAINT "Store_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProductCategory" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "ProductCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProductCategoryAssignment" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INT4 NOT NULL,
    "product_category_id" INT4 NOT NULL,

    CONSTRAINT "ProductCategoryAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "store_id" INT4 NOT NULL,
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,
    "price" FLOAT8 NOT NULL,
    "storeId" INT4,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PurchaseOrder" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "buyer_id" INT4 NOT NULL,
    "purchase_date" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PurchaseOrder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PurchaseOrderProductAssociation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "purchase_order_id" INT4 NOT NULL,
    "product_id" INT4 NOT NULL,
    "quantity" INT4 NOT NULL,

    CONSTRAINT "PurchaseOrderProductAssociation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProductPhoto" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INT4 NOT NULL,
    "resource_url" STRING NOT NULL,

    CONSTRAINT "ProductPhoto_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StorePhoto" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "store_id" INT4 NOT NULL,
    "resource_url" STRING NOT NULL,

    CONSTRAINT "StorePhoto_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Auth_email_key" ON "Auth"("email");

-- AddForeignKey
ALTER TABLE "Buyer" ADD CONSTRAINT "Buyer_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "Auth"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Seller" ADD CONSTRAINT "Seller_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "Auth"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Seller" ADD CONSTRAINT "Seller_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductCategoryAssignment" ADD CONSTRAINT "ProductCategoryAssignment_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductCategoryAssignment" ADD CONSTRAINT "ProductCategoryAssignment_product_category_id_fkey" FOREIGN KEY ("product_category_id") REFERENCES "ProductCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseOrder" ADD CONSTRAINT "PurchaseOrder_buyer_id_fkey" FOREIGN KEY ("buyer_id") REFERENCES "Buyer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseOrderProductAssociation" ADD CONSTRAINT "PurchaseOrderProductAssociation_purchase_order_id_fkey" FOREIGN KEY ("purchase_order_id") REFERENCES "PurchaseOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseOrderProductAssociation" ADD CONSTRAINT "PurchaseOrderProductAssociation_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProductPhoto" ADD CONSTRAINT "ProductPhoto_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StorePhoto" ADD CONSTRAINT "StorePhoto_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
