const topSellingProductsExample = [
  { productName: "Yeti Tundra 65 Cooler", amount: 32 },
  { productName: "Coleman Sundome 4-Person Tent", amount: 45 },
  { productName: "Osprey Atmos AG 65 Backpack", amount: 23 },
  { productName: "MSR Hubba Hubba NX 2-Person Tent", amount: 11 },
  { productName: "ENO DoubleNest Hammock", amount: 63 },
  { productName: "Jetboil Flash Cooking System", amount: 19 },
  { productName: "Therm-a-Rest NeoAir XTherm Sleeping Pad", amount: 36 },
  { productName: "Black Diamond Spot Headlamp", amount: 10 },
  { productName: "Patagonia Down Sweater Jacket", amount: 35 },
  { productName: "Garmin inReach Explorer+ Satellite Communicator", amount: 29 },
  { productName: "Hydro Flask 32 oz Wide Mouth Water Bottle", amount: 34 },
  { productName: "Columbia Men's Newton Ridge Plus II Hiking Boots", amount: 36 },
  { productName: "Arc'teryx Beta AR Jacket", amount: 15 },
  { productName: "Goal Zero Yeti 400 Portable Power Station", amount: 8 },
  { productName: "Katadyn Hiker Pro Water Filter", amount: 14 },
  { productName: "Garmin Fenix 6 Multisport GPS Watch", amount: 18 },
  { productName: "Big Agnes Q-Core SLX Sleeping Pad", amount: 19 },
  { productName: "Black Diamond Trail Ergo Cork Trekking Poles", amount: 23 },
  { productName: "Sawyer Products Mini Water Filtration System", amount: 26 },
  { productName: "Keen Women's Targhee II Mid Waterproof Hiking Boots", amount: 27 },
  { productName: "Osprey Ultralight Stuff Pack", amount: 2 },
  { productName: "MSR WhisperLite International Backpacking Stove", amount: 1 },
  { productName: "Nemo Dagger 2P Ultralight Backpacking Tent", amount: 1 },
  { productName: "Rumpl Original Puffy Blanket", amount: 7 },
  { productName: "Petzl Tikka Headlamp", amount: 8 },
  { productName: "Arc'teryx Beta SL Hybrid Jacket", amount: 10 },
  { productName: "REI Co-op Flexlite Camp Chair", amount: 10 },
  { productName: "MSR PocketRocket 2 Mini Stove Kit", amount: 2 },
  { productName: "Thule RoundTrip Ski Roller Bag", amount: 1 },
  { productName: "Salomon Quest 4D 3 GTX Hiking Boots", amount: 20 },
];


export default topSellingProductsExample;